Yong
willtyler98/SourceHub pull request #19
Opened 2019-03-30 02:23 UTC by Bong3652

2019-03-30 02:46 UTC, Will-Tyler requested changes
Please fix the constraint issues and remove the print statements that print out all of the repos

2019-03-30 20:30 UTC, Bong3652 commented
can you tell me which constraints I need to fix I dont think i fixed it

2019-03-30 21:59 UTC, willtyler98 commented
I can't really tell which ones are causing the constraint issues. My advice is to just get it working with a UITableViewCell by using the textLabel and detailTextLabel that come with that. For the feed view controller, I got it working without setting up constraints for the cells

2019-04-04 00:44 UTC, Will-Tyler approved these changes

2019-04-04 00:44 UTC, merged